# Generated by Django 5.1.5 on 2025-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=64, null=True)),
                ('energy_choice', models.TextField(max_length=64)),
                ('emotion', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, max_length=512, null=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
