# Generated by Django 5.1.5 on 2025-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_useremotiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremotiondata',
            options={'verbose_name_plural': 'User Emotion Data'},
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='energy_choice',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
