# Generated by Django 5.1.5 on 2025-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_useremotiondata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotiondata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='name',
            field=models.CharField(blank=True, default='Anonymous user', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='reason',
            field=models.TextField(blank=True, default='Chose not to share.', max_length=512, null=True),
        ),
    ]
