# Generated by Django 5.1.5 on 2025-01-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_useremotiondata_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='emotion',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='type',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=16),
        ),
        migrations.AlterField(
            model_name='emotiongroup',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emotions', to='onboarding.emotion'),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='energy_choice',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='name',
            field=models.CharField(blank=True, default='Anonymous user', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='reason',
            field=models.TextField(blank=True, default='Chose not to share.', max_length=256, null=True),
        ),
    ]
