# Generated by Django 5.1.5 on 2025-01-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_useremotiondata_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotiondata',
            name='emotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_emotions', to='onboarding.emotion'),
        ),
    ]
