# Generated by Django 5.1.5 on 2025-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_useremotiondata_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotiondata',
            name='emotion',
            field=models.CharField(max_length=32),
        ),
    ]
