# Generated by Django 5.1.5 on 2025-01-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_alter_useremotiondata_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotiondata',
            name='reason',
            field=models.TextField(default='Chose not to share.', max_length=256, null=True),
        ),
    ]
