# Generated by Django 5.1.5 on 2025-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_alter_useremotiondata_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='type',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='useremotiondata',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Anonymous user', max_length=32, null=True),
        ),
    ]
